# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picsart', '0002_auto_20180610_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
